name: Build and Obfuscate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: 8.1

      # Step 3: Install Composer dependencies from /src/
      - name: Install Composer Dependencies
        run: |
          cd src
          composer install

      # Step 4: Clone and set up YAK Pro PHP Obfuscator
      - name: Install YAK Pro PHP Obfuscator
        run: |
          git clone https://github.com/pk-fr/yakpro-po.git
          cd yakpro-po
          composer install

      # Step 5: Configure and run the obfuscator
      - name: Obfuscate Source Code
        run: |
          cp yakpro-po/yakpro-po.cnf.default yakpro-po/yakpro-po.cnf
          sed -i 's|source_directory:.*|source_directory: "./src"|' yakpro-po/yakpro-po.cnf
          sed -i 's|target_directory:.*|target_directory: "./dist"|' yakpro-po/yakpro-po.cnf
          php yakpro-po/yakpro-po.php

      # Step 6: Deploy obfuscated code
      - name: Deploy Obfuscated Code
        run: |
          echo "Deploying obfuscated code..."
          # Add your deployment commands here
