name: Build Static PHP Binary

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader
        working-directory: ./path-to-your-project # Adjust this if composer.json is in a subdirectory
      

      # Step 2: Install dependencies (Composer)
      - name: Install PHP dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust PHP version as needed
      - run: composer install --no-dev --optimize-autoloader

      # Step 3: Download static-php-cli
      - name: Download Static PHP CLI
        run: |
          curl -L -o static-php-cli https://github.com/crazywhalecc/static-php-cli/releases/latest/download/static-php-cli-linux
          chmod +x static-php-cli

      # Step 4: Build the PHP binary
      - name: Build PHP Binary
        run: |
          ./static-php-cli build --source-dir=./ --output=cookiecms
          chmod +x php-binary

      # Step 5: Archive the binary
      - name: Archive PHP Binary
        run: tar -czf php-binary.tar.gz php-binary

      # Step 6: Upload the binary to GitHub release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./php-binary.tar.gz
          asset_name: php-binary.tar.gz
          asset_content_type: application/gzip
