name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh                          # Ensure the .ssh folder exists
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa # Write the private key
        chmod 600 ~/.ssh/id_rsa                 # Set strict permissions

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@45.136.71.90 "cd /var/www/cookiecms/ && docker compose stop && git pull origin main && docker compose up -d"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
