name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /var/www/cookiecms
        git pull origin main
        # Если используется Docker, перезапустите контейнеры
        #docker-compose down
        #docker-compose up -d --build
        EOF
